baseURL: https://yoannlr.github.io/

# pour le rss
languageCode: fr-fr
# pour la localisation de la date
defaultContentLanguage: fr

title: yoannlr, notes d'un admin sys
theme: yoannlr

disableKinds:
  # /categories, /tags
  - taxonomy
  # /categories/article, /tags/linux...
  - term

# taille du paginator
pagination:
  pagerSize: 8

markup:
  highlight:
    style: vs

params:
  counting:
    # https://jasoncameron.dev/abacus/
    enable: true
    namespace: yoannlr.github.io
